
party_keywords = {
    "bjp": ['bjp', 'modi', 'amitshah', 'pratap_sarangi', 'rajnathsingh', 'myogiadityanath', 'indiawithmodi',
            'bengalwithnamo', 'bengalwithbjp', 'bengalwelcomesmodi', 'pmmodi', 'narendramodi', 'mamtabanerjeekojaishriram',
            'jaishriram', 'modiji', 'dhekiajuliwelcomesmodi', 'bjpgorbesonarbangla', 'atmanirbharpurvibharat', 'godimedia', 'bengalrejectsmodi',
            'bengalrejectsbjp', 'idiotpmmodi', 'feku', 'modiglobaldisaster', 'idiotpm', 'boycottbjp', 'chaiconspiracy', 'antifarmlaws',
            'worldrenownedliar', 'modidhongihai', 'ram_card', 'modiinbengal', 'nirmalasitharaman', 'gretathunberg', 'modiwithfarmers',
            'bengalwelcomespm', 'bjpgoonsattackingfarmers', 'rishiganga', 'pmoindia', 'wearewithutearakhand', 'prayforuttarakhand', 'poribortonyatra',
            'rss', 'glaciar_burst', 'chamoli', 'pmfloodfund', 'pmmodibusy', 'releasenodeepkaur', 'breakingnews', 'attack',
            'bjpfailsindia', 'bjppetroltaxloot', 'runformodi', 'modi_rojgar_do', 'pradeepteamattacked', 'naukaridoyadegreewapaslo', 'pamelagoswami',
            'suvenduadhikari', 'gobackmodi', 'chonkidaarchorhai', 'bjpthepartyisover', 'saffron_party', 'uttarakhanddisaster', 'hindu_muslim_propaganda',
            'bjpinsultsmaadurga', 'bjpagainstnation', 'bjpagainstfarmers', 'bjp_against_true_indians', 'fuelloot', 'cocaine', 'junkiesofbjp',
            'bhakt', 'bjpyouthleaderpamela', 'pameladrugs', 'bjpsehobena', 'petroldieselpricehike', 'petrolprice', 'petrolpricehike', 'dieselprice',
            'justiceforsushantsinghrajput', 'justice4dishasalian', 'dpstopintimidatingfarmers', 'ebarbanglaybjp', 'bengalbudgetforall', 'istandwithfarmers', 'sonarbangla',
            'rollbackmoditax', 'releasedetainedfarmers', 'caa', 'amitshahinbengal', 'amitshahji', 'railrokoforfarmers', 'bjpforbengal',
            'poribortoninbengal', 'sonarbanglaelectrified', 'kisanaandolan', 'shahvsmamata', 'teamnamo', 'vote4modi', 'modifuelscam',
            'looteribjp', 'modihikespetrolprice', 'bjpsebetibachao', 'chaiwala', 'save_unnao_ki_beti', 'dilipghoshbjp', 'pariwartanyatra',
            'jpnadda', 'modigovt', 'petrol100', 'farmlaws', 'rakeshtikait', 'yashdasgupta', 'mithunchakraborty', 'jumla_for_bengal',
            'rammandir', 'releasedisharavi', 'dineshtrivedi', 'farmbills2020', 'toolkitexposed', 'gretatoolkit', 'gretathunbergtoolkit', 'mohanbhagwat',
            'justicedueinssrcase', 'iamagainstmodigovt', 'pmkisan', 'supportfarmers', 'pmcares', 'ramkanaam',
        
            "modibrigaderally","modirsathebrigade","modirsathebangla","asolparibortan","bjpbrigade",
            "mithunda","brigadeground","brigadecholo","pmofindia","modi_job_do","bjpfailsindia",
            "modivowsasolporibortan","poribortonerbrigade","indiaagainstlpgloot","aarnoy_aarnoy",
            "gautamgambhir","bjpcdscandal","modi_msp_do","stopprivatisation","byebyebjp",
            "savebengalfromtmcbjp","ashokdinda","farmerscall_bjpboycott","prashantkishor",
            "pradeepbhandari","lpgpricehike","pradeepinbengal","bengalwithbhagwa","bjp4bangal",
            "hinduslivesmatter","pmmodibrigaderally","bjp4goghat","brigadecholobengal","tmc_hatao_bjp_lao",
            "saffrontsunami","mypmmypride","modihaitohmumkinhai","mithunchakrabortyjoinsbjp",
            "novotetobjp","modistormskolkata","bharatbandh","100daysfarmersprotest","swagatamyogiji",
            "rssterrorism","bjpvsmamta","lokkhosonarbangla","shubhenduadhikari","suvenduvsmamata",
            "100daysofbjparrogance","ebarbanglaybjp","mamatavssuvendu","shubhendu","kailashvijayvargiya",
            "gorbosonarbangla","amitmalviya","bjpforsonarbangla","bjp4ind","notobjp","farmersbeforevotes",
            "3monthsofdelhiprotest","mannkibakwaas","speakupagainstpricerise","modivsmamata","novotetobjp",
            "defeatbjp","sanyuktkisanmorcha","bku","upcm","chiefministerup","yogiadityanath","bjpup",
            "agriculturallaw","100_day_farmer_movement","bengalmaangeporibortan","rajib_banerjee",
            "farmersrallyinbengal","gorakhpur","acchedin","babulsupriyo","modiraidsprofarmers","adityanathkarakshasraaj",
            "nojob_novote","rejectbjpjungleraj","shuvenduadhikari","godhramassacre","chandrashekharazad",
            "narottammishra","vanideviformlc","voteforvanidevi","hathras","yogivogihai","outsiders","modi_jawab_do",
            "savehindus","revivegreatbengal","hathrascase","drmanishkumar","bjpflopshow","bjptoolkit",
            "bjpexposed","shameonbhakts","sambitpatra","jitendratiwari","examwarriors","modigovt",
            "farmersbeforevotes","hathrasrape_again","garvsekahohamhinduhain","yogiangryspeech",
            "justiceforhathraskibeti","bjpsesabpareshan","moditax","looteribjp","cmyogi","jitendratiwari",
            "tmc_hatao_bjp_lao","stophindimigration","endhindiimposition","stophindiimperialism","sambitpatra",
            "ramdrohi_par_rann","bjphataobetibachao","cowsmuggling","swagatamyogiji","puducherrywelcomesmodiji",
            "wastebjp","modionbrokenchair","srabantichatterjee","pmspeakuponssrcase","shivrajsinghchouhan",
            "tomarmodikisanvirodhi","sankalppatra","agriculturallaws","vote4sonarbangla","banglayaschebjp",
            "sonarbanglasonkolpopotro","voteforbjp","bengalrejectsgujaratimanifesto","deepakprakash",
            "modirsatheiasolporiborton","bjperongikarsonarbangla","bjpsankalppatra","bjpmanifesto","homeminister",
            "banglayaschebjpdidi","modimadedisaster","pmmodiinbankura","bengalbjpjokers","modiexposed",
            "baranagarebjpchai","gobackmodi","modigovt4ambaniadani","fekuinbengal","assetmonetisation",
            "godimediasedeshbachao","modinotwelcome","madanruidas","bjpfearskejriwal","banglachaebjpmodel",
            "bhainsariots","jumla_nahin_msp_do","300deathsatprotest","nofarmers_nofood","godimediaantifarmer",
            "goyalghoregutoguti","bhagwabengal","ebarsonarbangla","arungovil","savejagannathland","fuddupm",
            "rahulsinha","mukulroy","bjpdestroysdemocracy","bjpagainstdemocracy","modiharassingprofarmers",
            "arjunsingh","bjpcdscandal","fight_for_farmer_right","bjp_mukt_bharat","modisoldindia",
            "puruliawelcomesmodiji","namovolunteer","bankstrike","pvtpmoltd","centralgovt","ayegatomodihi",
            "oilprice","bankstrikebankers","smritiirani","swapandasgupta","banglayamitshah","bjpmaanenirbhoyjanata",
            "bankprivatisation","nirupammukherjee","atmanirbharbharat","bengalwithrajnath","cmyogiinbengal",
            "farmersroarinbengal","yogiroxx","bongerbhumiteshah","bjpfails","tadipar","releaseranjitsingh",
            "agriculture_bill_benefit_nill","istandwithfarmers","bjpworkerswestbengal","punishantifarmerbjp",
            "striketosaveindia","bengalchahebjp","shameonbjp","sanatanadharma","ashoklahiri","bjpmp","babulupriyo",
        
            "bjp4sonarbangla","saumitrakhan","rafaelscam","ebarsonarbanglaebarbjp","parikshapecharcha",
            "parikshapecharcha2021","bjpelectioncampaign","rafale","shahnawazhussain","novoteto_liarmodi",
            "rajibbanerjee","novoteforbjp","novotetobjp","anti_farmer_rss","ebarhobeasolporiborton",
            "india_with_rss","bjphataodeshbachao","bjpanbeasolporiborton","hinduecosystem","amarvotebjpke",
            "kissanektazindabad","evmtheftbybjp","hindutemples","modiwave","rahulsinha","metroman4palakkad",
            "dipakhaldar","modilies","100crorekivasuli","prabirghoshal","bjpwinbangal","chowkidarhichorhai",
            "bjpkillsdemocracy","sonarbanglagorbebjp","amarvotebjpke","ebarsonarbanglaebarbjp","antimodiliberals",
            "freetntemples","itrustamitshah","touristhomeminister","nandigramwithbjp","pmo","chattisgarhnaxalattack",
            "bjptsunamiinassam","bijapurencounter","resignamitshah","bijapur","cookingoil","communalhatred",
            "nationalsecurity","bijapurnaxalattack","desh_ka_gaddar_rss","lashkar_e_rss","modipara",
            "askyourprimeminister","fakemodiwave","lielikemodi","standwithbengalhindus","injusticewithrrbs",
            "nobjp","chaiwala","mautkasaudaghar","banglarghoreghorebjp","2april_countrywideprotest","motabhai",
            "keralawithmodi","ramraj","blockgodimediaonsocialmedia","mukhtaransari","evmtheftbybjp",
            "ebarhobeasolporiborton","saffronbengal","mannkibaat","allbhaktunion","modibhakts","arrestnarsinganand",
            "evmchorbjp","banglarunnotitebjpchai","bjpbagdah","modiuncle","waahmodijiwaah","bengalbhagwahoga",
            "bjponcemoreinassam","assamwantsbjpagain","biplabkumardeb","locketchatterjee","shovamajumdar",
            "justiceforshova","bjpitcell","langdi_tmc_or_atmanirbhar_bjp","evm_theft_assam","wasimrizwi",
            "assamevm","assamevmscandal","amitshahroadshow","farmersagainstatrocities","modifoolday",
            "bjpevmloot","centralgovernment","bjpvsdidi","bjpgoons","operationlotusfailed","ebarbjpsarkar",
            "modihaitomumkinhai","vanakammodiji","evmchorchowkidar","lotus","gobackfascistmodi","kisanektamorcha",
            "kisanmazdoorektazindabad","vikashobe","modimadedisaster","cheaterbjp","modigoback","doubleengine",
            "deshdrohibjp","bjpdestroyedindia","pmcaresfund","nationwithyogiji","modidiwas","missionlotus",
            "vote4sonarbangla","kirronkher","girirajsingh","nandigramwithbjp","devendrafadnavis","modiinbangladesh",
            "modidivas","globalfekuday","oversightfm","ashokdinda","modiontram","completejustice4ssr",
            "nationaljumladay","assamwantsbjpagain","novottorss","globalfekuday","globalfenkuday","dhflscam",
            "jumlajividivas","feku2021","befeku","achhedin","dadasahebphalkeaward","liendranamo","mahavasooliaghadi",
            "trustbjp","voteforsuvenduadhikari","extend_due_dates","sisiradhikari","banglabjpkchaina",
            "bjp_supporter_here","smallsavings","annaatthe","oversight","bjp_anti_national","voteformodi",
            "rohingya","rohingyas","no_msp_no_vote","kumbhmela2021","modigovtsenahopayega","modifailsindia",
            "modihataodeshbachao","modiresign","modimadecrisis","resignmodi","nashikoxygenleak","indianeedsoxygen",
            "ebarbjpsorkar","mautkasaudagar","resignnarendramodi","shameonbjp","shameonmodi","modicovidaddress",
            "modispeech","modiresignorrepeal","kumbhmela_coronahotspot","pmaddresstonation","tanmayfadnavis",
            "devendrafadnavis","vaccinejumla","modistopelectionrallies","modihaitomumkinh","bjphattrick",
            "pmdoesnotcare","bjp200plusinbengal","nation_with_modi","hindurashta","extendallduedatesimmediately",
            "extend_due_dates_immediately","modiketouristscoronalaaye","ghazipurborder","singhuborder",
            "privatizationbigscam","piyushgoyal","anantsinghvsamitshah","mukulroy","nationwithmodi",
            "modi_in_bengal_elections","coronautsav","superspreadermodi","chaukidaar","pmresignation",
            "harshvardhanshouldresign","modi_is_a_bad_omen","shameongujaratgovernment","pracharminister",
            "bjpspreadingvirus","mahakumbh","modimustresign","nomorebjp","superspreader","modi_is_best_bet",
            "bjpresponsibleforcoronainindia","gopalsaha","achedinaagaye","repeallawstoendprotest",
            "primemoron","whereispm","covidiotgoyal","pmcaresscam","shamelessmodi","smritionrbangla",
            "bjp_bengal_elections","gobar","vaccineshortage","bjphoardingremdesivir","bengalrejectsgujaratimanifesto",
            "remdesivirblackmarketing","bjpwillwinbengal","sayantanbasu","carelessmodi","pmcbankcrisis","kumbh",
            "merchantofdeath","istandwithbandisanjay","banbjp","khubhmela","ebarbanglaraebjp","jumlaparty",
            "bjp4pursurah","banglarmanushbjpersathe","postponendaexam","banelectionralliesincovid",
            "bjploveselectionthanvoters","worstpmever","fakekissanandolan","haridwarmahakumbh2021","postponekumbh",
            "mahavinashaghadi","democracy_converted_into_brahminocracy","kumbhcorona","votebjp4sonarbangla",
            "votebjp4gobarbangla","absenteepm","bjptwohundredplus","stopsuperspreaderevents","pmcarefund",
            "kumbhduringcovid","postponejee2021","postponejee","postponejeemains2021","boycottceat",
            "narendermodi"
            ],

    "tmc": ["tmc","trinamoolcongress","mamata","banerjee","mamtabanerjeekojaishriram","tmchataobanglabachao","didi",
            "murderermamata","duaresarkar","paraysamadhan","mamtabanerjee","abhishekbanerjee","bhaipo","breakingnews",
            "attack","bangladidirthekemuktichay","tukdetukde","didikebolo","banglanijermeyekeichay","khelahobe","didirdoot",
            "joybangla","pishijao","pishijoyshreeram","bengalwantsitsowndaughter","jihadididi","jakirhossain",
            "shahvsmamata","upenbiswas","saradhascam","zakirhussain","bombattack","zakirattack","zakirhussainminister",
            "mumtazbano","rohingyajamaat","azaannoisefree","standwithdilipmandal","maakitchen","maakirasoi",
        
            "cmofbengal","hemantsoren","speakhindiandlose","prashantkishore","10ermichil",
            "vivekgupta","hinduhatingtmc","mamtabano","bjpvsmamta","suvenduvsmamata","mamatavssuvendu",
            "mamta","siddiqullahchowdhury","bengalwithdidi","paliyegelomamata","didishowstheway",
            "nototmc","tmc180plus","didinandigramdare","saayonighosh","trinamoolcongresszindabaad",
            "maamatimaunshzindabaad","mamatabanerjeezindabaad","voteforaitc","tmccandidatelist",
            "banglanijermekeichai","modivsmamata","sharda","narda","ponzi","anubratamondal",
            "juibiswassocial","juibiswaslive","mamtaaspmin2024","cmmamatabanerjee","sanjayraut",
            "uddhavinsultsarmy","akhileshyadav","tejashwiyadav","tmcvsmuslimfront","sayantikabanerjee",
            "tmchhi","tmchataobanglabachao","nachiketachakraborty","subratamukherjee","tmcgoons",
            "bengalwithdidi","bengalkibeti","khelasheshhobe","didirsathebangla","didirunnayanerkhelahobe",
            "tmcmanifesto","banglargorbomamata","didir10ongikar","bengalwantsdidiagain","banglargorbomamata",
            "votefordidi","junemaliah","sujoybanerjee","tmcterror","nusratjahan","janatawithmamata","mahuamoitra",
            "tmcisfraud","removemamta","parthachatterjee","fakeitlikepishi","vote4rathinghosh","rathinghoshmla",
            "tatatrinamool","khelakhotamhobe","tatadidi","didikadrama","arrogantdidi","mamataisback",
            "bantibablirajasthanaao","khelatohhobe","khailahobe","134nowardtmc","banerjeebaganunit","mamta_pk_drama",
            "mamtadrama","tmc_nautanki","tmckadarama","mamataketooltikait","mamtadrama","banglachorerpisikechayna",
            "mamtahurt",
            
            "didiodidi","banglanijermaykechai","tmczindabad","vivekguptaamohero","voteforvivekgupta",
            "dididontcry","yashwantsinha","evm_chor_tmc","jayabachchan","sujatamondalkhan","kanchanmullick",
            "gautamghosh","votefortmc","tmcsweepsphase1","momtabegum","2maydiditatabyebye","coalmafiascam",
            "momtabano","madanmitra","manasmajumdar","jihadidi","didi_delhi","tmcvotecampaign","2maydidigai",
            "tmcsweepsphase2","pishiharchebanglajitche","omprakashmishra","supportomprakashmishra",
            "banglargorbomamata","raagkenodidi","derekobrien","bjpvsdidi","mamatamuslimmessage",
            "mamataloosingnandigram","pisimuktobanglachai","phishi","asbetohdidi","didikadrama","didirsathenandigram",
            "mamtaisnotdidi","mamataislosing","derek","shandilya","tmcloosingbengal","nandigramjeetchedidi",
            "didikadarr","maamaatimanush","maa","banglanijermeyekeichay","firhadhakim","koushanimukherjee",
            "mamatatapecontroversy","ssc_jawab_do","postpone_chsl2020","postpone_ssc_chsl","2maydidijache",
            "sscchslpostpone","didikedingaye","tmcchorhai","sscchslexampostpone","dalitbirodhitmc",
            "trinamoolcongresswins"
            ],

    "leftfront": ["congressmuktbharat","vote4left","congresswithnaxals","liberalismisamentaldisorder","rahulgandhi",
                  "congresskakuchnhihosakta","rahulinsultsvoters","pappu","shameon_inc","bloodonyourhands_raulgandhi",
                  "shameon_congressparty","congressinsultsassam","congresstowininelections21","congressforindia"
                  "pappudiwas","pappufailhogaya","pappucongress","congressbetrayedfarmers","soniyagandhi","pappupolicy",
                  "bam_evm","byebyecongress","congressbetrayedindia","congress_bhagao_assam_bachao","pappudivas",
                  "pappuday","myvoteforcongress","pappukamandatorybreak","leftists","happyrahulgandhiday",
                  "priyankagandhivadra","vote4shadabkhan","rahulrajya","rahulglobalinsult","visonaryrahul",
                  "drmanmohansingh","rahulshamesindia","rahulsuspendspoliticalrallies","rahulgandhirallies",
                  "rahulgandhiwithassam","rahulgandhivoiceofindia","congresskevichaar","congressmodel","sanjuktamorcha",
                  "fakegandhiclan","pappugang","pappuinbangkok",

                  "jyotibasu","leftfront","aisf","buddhadebbhattacharjee","isf","tmcvsmuslimfront",
                  "abbassiddiqui","furfurasharif","aimim","bengalmangecongress","congresspseudosecularism",
                  "bengalrejectscongress","congress","anandsharma","adhirranjan","congressalliance",
                  "congressagainsthindus","sachinpilot","asaduddinowaisi","sitaramyechuri","congresscandidatelist",
                  "vote4sanjuktamorcha","vote4congress","myleaderrahulgandhi",
                  
                  "left", "cpi", "marxist","leftlibgang","bengalneedsleft","communists","left_congress_alliance",
                  "cpim","leftvspolice"
                  ]
}
