#extras only not the commons
#a1 finished
#a2 finished
party_keywords = {
    "bjp": ["bjp4sonarbangla","saumitrakhan","rafaelscam","ebarsonarbanglaebarbjp","parikshapecharcha",
            "parikshapecharcha2021","bjpelectioncampaign","rafale","shahnawazhussain","novoteto_liarmodi",
            "rajibbanerjee","novoteforbjp","novotetobjp","anti_farmer_rss","ebarhobeasolporiborton",
            "india_with_rss","bjphataodeshbachao","bjpanbeasolporiborton","hinduecosystem","amarvotebjpke",
            "kissanektazindabad","evmtheftbybjp","hindutemples","modiwave","rahulsinha","metroman4palakkad",
            "dipakhaldar","modilies","100crorekivasuli","prabirghoshal","bjpwinbangal","chowkidarhichorhai",
            "bjpkillsdemocracy","sonarbanglagorbebjp","amarvotebjpke","ebarsonarbanglaebarbjp","antimodiliberals",
            "freetntemples","itrustamitshah","touristhomeminister","nandigramwithbjp","pmo","chattisgarhnaxalattack",
            "bjptsunamiinassam","bijapurencounter","resignamitshah","bijapur","cookingoil","communalhatred",
            "nationalsecurity","bijapurnaxalattack","desh_ka_gaddar_rss","lashkar_e_rss","modipara",
            "askyourprimeminister","fakemodiwave","lielikemodi","standwithbengalhindus","injusticewithrrbs",
            "nobjp","chaiwala","mautkasaudaghar","banglarghoreghorebjp","2april_countrywideprotest","motabhai",
            "keralawithmodi","ramraj","blockgodimediaonsocialmedia","mukhtaransari","evmtheftbybjp",
            "ebarhobeasolporiborton","saffronbengal","mannkibaat","allbhaktunion","modibhakts","arrestnarsinganand",
            "evmchorbjp","banglarunnotitebjpchai","bjpbagdah","modiuncle","waahmodijiwaah","bengalbhagwahoga",
            "bjponcemoreinassam","assamwantsbjpagain","biplabkumardeb","locketchatterjee","shovamajumdar",
            "justiceforshova","bjpitcell","langdi_tmc_or_atmanirbhar_bjp","evm_theft_assam","wasimrizwi",
            "assamevm","assamevmscandal","amitshahroadshow","farmersagainstatrocities","modifoolday",
            "bjpevmloot","centralgovernment","bjpvsdidi","bjpgoons","operationlotusfailed","ebarbjpsarkar",
            "modihaitomumkinhai","vanakammodiji","evmchorchowkidar","lotus","gobackfascistmodi","kisanektamorcha",
            "kisanmazdoorektazindabad","vikashobe","modimadedisaster","cheaterbjp","modigoback","doubleengine",
            "deshdrohibjp","bjpdestroyedindia","pmcaresfund","nationwithyogiji","modidiwas","missionlotus",
            "vote4sonarbangla","kirronkher","girirajsingh","nandigramwithbjp","devendrafadnavis","modiinbangladesh",
            "modidivas","globalfekuday","oversightfm","ashokdinda","modiontram","completejustice4ssr",
            "nationaljumladay","assamwantsbjpagain","novottorss","globalfekuday","globalfenkuday","dhflscam",
            "jumlajividivas","feku2021","befeku","achhedin","dadasahebphalkeaward","liendranamo","mahavasooliaghadi",
            "trustbjp","voteforsuvenduadhikari","extend_due_dates","sisiradhikari","banglabjpkchaina",
            "bjp_supporter_here","smallsavings","annaatthe","oversight","bjp_anti_national","voteformodi",
            "rohingya","rohingyas","no_msp_no_vote","kumbhmela2021","modigovtsenahopayega","modifailsindia",
            "modihataodeshbachao","modiresign","modimadecrisis","resignmodi","nashikoxygenleak","indianeedsoxygen",
            "ebarbjpsorkar","mautkasaudagar","resignnarendramodi","shameonbjp","shameonmodi","modicovidaddress",
            "modispeech","modiresignorrepeal","kumbhmela_coronahotspot","pmaddresstonation","tanmayfadnavis",
            "devendrafadnavis","vaccinejumla","modistopelectionrallies","modihaitomumkinh","bjphattrick",
            "pmdoesnotcare","bjp200plusinbengal","nation_with_modi","hindurashta","extendallduedatesimmediately",
            "extend_due_dates_immediately","modiketouristscoronalaaye","ghazipurborder","singhuborder",
            "privatizationbigscam","piyushgoyal","anantsinghvsamitshah","mukulroy","nationwithmodi",
            "modi_in_bengal_elections","coronautsav","superspreadermodi","chaukidaar","pmresignation",
            "harshvardhanshouldresign","modi_is_a_bad_omen","shameongujaratgovernment","pracharminister",
            "bjpspreadingvirus","mahakumbh","modimustresign","nomorebjp","superspreader","modi_is_best_bet",
            "bjpresponsibleforcoronainindia","gopalsaha","achedinaagaye","repeallawstoendprotest",
            "primemoron","whereispm","covidiotgoyal","pmcaresscam","shamelessmodi","smritionrbangla",
            "bjp_bengal_elections","gobar","vaccineshortage","bjphoardingremdesivir","bengalrejectsgujaratimanifesto",
            "remdesivirblackmarketing","bjpwillwinbengal","sayantanbasu","carelessmodi","pmcbankcrisis","kumbh",
            "merchantofdeath","istandwithbandisanjay","banbjp","khubhmela","ebarbanglaraebjp","jumlaparty",
            "bjp4pursurah","banglarmanushbjpersathe","postponendaexam","banelectionralliesincovid",
            "bjploveselectionthanvoters","worstpmever","fakekissanandolan","haridwarmahakumbh2021","postponekumbh",
            "mahavinashaghadi","democracy_converted_into_brahminocracy","kumbhcorona","votebjp4sonarbangla",
            "votebjp4gobarbangla","absenteepm","bjptwohundredplus","stopsuperspreaderevents","pmcarefund",
            "kumbhduringcovid","postponejee2021","postponejee","postponejeemains2021","boycottceat",
            "narendermodi"
            ],

    "tmc": ["didiodidi","banglanijermaykechai","tmczindabad","vivekguptaamohero","voteforvivekgupta",
            "dididontcry","yashwantsinha","evm_chor_tmc","jayabachchan","sujatamondalkhan","kanchanmullick",
            "gautamghosh","votefortmc","tmcsweepsphase1","momtabegum","2maydiditatabyebye","coalmafiascam",
            "momtabano","madanmitra","manasmajumdar","jihadidi","didi_delhi","tmcvotecampaign","2maydidigai",
            "tmcsweepsphase2","pishiharchebanglajitche","omprakashmishra","supportomprakashmishra",
            "banglargorbomamata","raagkenodidi","derekobrien","bjpvsdidi","mamatamuslimmessage",
            "mamataloosingnandigram","pisimuktobanglachai","phishi","asbetohdidi","didikadrama","didirsathenandigram",
            "mamtaisnotdidi","mamataislosing","derek","shandilya","tmcloosingbengal","nandigramjeetchedidi",
            "didikadarr","maamaatimanush","maa","banglanijermeyekeichay","firhadhakim","koushanimukherjee",
            "mamatatapecontroversy","ssc_jawab_do","postpone_chsl2020","postpone_ssc_chsl","2maydidijache",
            "sscchslpostpone","didikedingaye","tmcchorhai","sscchslexampostpone","dalitbirodhitmc",
            "trinamoolcongresswins"
            ],

    "leftfront": ["congressmuktbharat","vote4left","congresswithnaxals","liberalismisamentaldisorder","rahulgandhi",
                  "congresskakuchnhihosakta","rahulinsultsvoters","pappu","shameon_inc","bloodonyourhands_raulgandhi",
                  "shameon_congressparty","congressinsultsassam","congresstowininelections21","congressforindia"
                  "pappudiwas","pappufailhogaya","pappucongress","congressbetrayedfarmers","soniyagandhi","pappupolicy",
                  "bam_evm","byebyecongress","congressbetrayedindia","congress_bhagao_assam_bachao","pappudivas",
                  "pappuday","myvoteforcongress","pappukamandatorybreak","leftists","happyrahulgandhiday",
                  "priyankagandhivadra","vote4shadabkhan","rahulrajya","rahulglobalinsult","visonaryrahul",
                  "drmanmohansingh","rahulshamesindia","rahulsuspendspoliticalrallies","rahulgandhirallies",
                  "rahulgandhiwithassam","rahulgandhivoiceofindia","congresskevichaar","congressmodel","sanjuktamorcha",
                  "fakegandhiclan","pappugang","pappuinbangkok",
                  ]
}
